from factory.factory_interface import Factory
from jobs.extractors.extract_json_job import ExtractJsonJob
from jobs.extractors.extract_demo_job import ExtractDemoJob

class ExtractorFactory(Factory):
	def __init__(self):
		super().__init__()

	def create(self, mode, **kwargs):
		merged_config = self.get_config(mode)

		#Autogenerated File Section. Do not Edit this file

		match mode:
			case "extract_json":
				return ExtractJsonJob(config=merged_config) #existing option
			case "extract_demo":
				return ExtractDemoJob(config=merged_config) #cool stuff, we have the comment intact as well
			case _:
				raise ValueError("Invalid extract type")
