from factory.factory_interface import Factory
from jobs.loaders.load_json_job import LoadJsonJob
from jobs.loaders.load_demo_job import LoadDemoJob

class LoaderFactory(Factory):
	def __init__(self):
		super().__init__()

	def create(self, mode, **kwargs):
		merged_config = self.get_config(mode)

		#Autogenerated File Section. Do not Edit this file

		match mode:
			case "load_json":
				return LoadJsonJob(config=merged_config)
			case "load_demo":
				return LoadDemoJob(config=merged_config)
			case _:
				raise ValueError("Invalid extract type")
