from factory.factory_interface import Factory
from jobs.transformers.transformer_json_job import TransformerJsonJob

class Factory(Factory):
	def __init__(self):
		super().__init__()

	def create(self, mode, **kwargs):
		merged_config = self.get_config(mode)

		#Autogenerated File Section. Do not Edit this file

		match mode:
			case "transformer_json_job":
				return TransformerJsonJob(config=merged_config)
			case _:
				raise ValueError("Invalid extract type")
